"""answer db

Revision ID: 11adad648124
Revises: 5dac7f768223
Create Date: 2020-08-30 11:26:07.133184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11adad648124'
down_revision = '5dac7f768223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_mark', sa.Column('testWasStarted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_mark', 'testWasStarted')
    # ### end Alembic commands ###
