"""final db v3

Revision ID: 127e036e74c1
Revises: a04043a47958
Create Date: 2020-09-13 01:54:25.780111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127e036e74c1'
down_revision = 'a04043a47958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('test', sa.Column('due_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'due_time')
    op.drop_column('test', 'due_date')
    # ### end Alembic commands ###
