"""test table

Revision ID: 264badc7518c
Revises: 4b6a323e8883
Create Date: 2020-08-08 21:48:45.532255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264badc7518c'
down_revision = '4b6a323e8883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('questiontext', sa.VARCHAR(length=140), nullable=True),
    sa.Column('test_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
