"""final db v3

Revision ID: 402bd6f93c79
Revises: 127e036e74c1
Create Date: 2020-09-13 10:27:40.405816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402bd6f93c79'
down_revision = '127e036e74c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_mark', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('test_mark', sa.Column('due_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_mark', 'due_time')
    op.drop_column('test_mark', 'due_date')
    # ### end Alembic commands ###
