"""final db v2

Revision ID: 7d6439926a0f
Revises: bddffbbe64eb
Create Date: 2020-08-31 11:40:58.805306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6439926a0f'
down_revision = 'bddffbbe64eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_mark', sa.Column('feedbackReleased', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_mark', 'feedbackReleased')
    # ### end Alembic commands ###
