"""final db v3

Revision ID: ca63d8ed2d9f
Revises: d8d5ffa4024d
Create Date: 2020-09-26 11:57:44.419406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca63d8ed2d9f'
down_revision = 'd8d5ffa4024d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('mark1Criteria', sa.String(length=50), nullable=True))
    op.add_column('unit', sa.Column('mark2Criteria', sa.String(length=50), nullable=True))
    op.add_column('unit', sa.Column('mark3Criteria', sa.String(length=50), nullable=True))
    op.add_column('unit', sa.Column('mark4Criteria', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'mark4Criteria')
    op.drop_column('unit', 'mark3Criteria')
    op.drop_column('unit', 'mark2Criteria')
    op.drop_column('unit', 'mark1Criteria')
    # ### end Alembic commands ###
