"""test finalized

Revision ID: cdf62aeabc7a
Revises: f059168e3b98
Create Date: 2020-08-09 10:55:35.590399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf62aeabc7a'
down_revision = 'f059168e3b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('isFinalized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'isFinalized')
    # ### end Alembic commands ###
