"""final db

Revision ID: d3e3fc88cd52
Revises: 0092fca0b4fd
Create Date: 2020-10-18 11:18:44.081220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e3fc88cd52'
down_revision = '0092fca0b4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('feedbackReleased', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'feedbackReleased')
    # ### end Alembic commands ###
