"""answer db

Revision ID: dce0ad618fce
Revises: 7d6439926a0f
Create Date: 2020-08-31 15:55:43.830624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce0ad618fce'
down_revision = '7d6439926a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_mark', sa.Column('hasBeenMarked', sa.Boolean(), nullable=True))
    op.add_column('test_mark', sa.Column('mark1', sa.Integer(), nullable=True))
    op.add_column('test_mark', sa.Column('mark2', sa.Integer(), nullable=True))
    op.add_column('test_mark', sa.Column('mark3', sa.Integer(), nullable=True))
    op.add_column('test_mark', sa.Column('mark4', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_mark', 'mark4')
    op.drop_column('test_mark', 'mark3')
    op.drop_column('test_mark', 'mark2')
    op.drop_column('test_mark', 'mark1')
    op.drop_column('test_mark', 'hasBeenMarked')
    # ### end Alembic commands ###
